# Generated by Django 3.1.6 on 2021-03-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email_address', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=49)),
                ('security_question', models.CharField(max_length=70)),
                ('security_answer', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TimerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerLabel', models.CharField(max_length=70)),
                ('start_time', models.DateTimeField(max_length=70)),
                ('end_time', models.DateTimeField(max_length=70)),
                ('total_time', models.DateTimeField(max_length=70)),
                ('start_switch', models.BooleanField()),
                ('end_switch', models.BooleanField()),
                ('start_primer', models.BooleanField()),
                ('end_primer', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeReport.user')),
            ],
        ),
    ]
